<?php
// Start output buffering to prevent header HTML from breaking AJAX
ob_start(); 
include('header.php');

// --- AJAX HANDLER FOR STATUS TOGGLE ---
if (isset($_POST['action']) && $_POST['action'] == 'toggle_status') {
    // Clear any HTML generated by header.php so we send ONLY the number
    ob_clean(); 
    
    $sn = $_POST['sn'];
    $table = $_POST['table'];
    $current_status = $_POST['status'];
    
    // Toggle logic: If 1, make 0. If 0, make 1.
    $new_status = ($current_status == 1) ? 0 : 1;
    
    $allowed_tables = ['gametime_new', 'gametime_manual'];
    
    if (in_array($table, $allowed_tables)) {
        // Ensure $con (database connection) is available from header.php
        $updateQuery = "UPDATE `$table` SET `active`='$new_status' WHERE `sn`='$sn'";
        if (mysqli_query($con, $updateQuery)) {
            echo $new_status; // Send strictly "0" or "1"
        } else {
            echo "error";
        }
    }
    exit; // Stop the script here so no footer HTML is added
}
// Flush buffer if not AJAX
ob_end_flush(); 
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Game Time Table</title>
    <style>
        /* --- GENERAL RESET --- */
        * { box-sizing: border-box; }
        body {
            background-color: #f4f6f9;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 0;
            -webkit-font-smoothing: antialiased;
        }

        /* --- PAGE TITLE --- */
        .page-title {
            text-align: center;
            font-size: 20px;
            font-weight: 700;
            padding: 15px 0;
            background: #fff;
            color: #333;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            position: sticky;
            top: 0;
            z-index: 100;
            margin-bottom: 20px;
        }

        /* --- MAIN WRAPPER --- */
        .main-content {
            max-width: 800px;
            margin: 0 auto;
            padding: 0 15px;
        }

        /* --- ORANGE HEADER STRIP --- */
        .table-header-row {
            background-color: #ff9800;
            color: white;
            display: flex;
            align-items: center;
            padding: 12px 15px;
            font-weight: 600;
            font-size: 14px;
            border-radius: 8px;
            margin-bottom: 10px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }

        .col-sno { width: 15%; text-align: left; }
        .col-game { width: 60%; text-align: left; padding-left: 5px; }
        .col-action { width: 25%; text-align: right; }

        /* --- CARD STYLE --- */
        .game-card {
            background: #ffffff;
            border-radius: 12px;
            padding: 15px;
            margin-bottom: 15px;
            display: flex;
            align-items: center;
            justify-content: space-between;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
            border-left: 5px solid #ff9800;
            transition: transform 0.2s;
        }

        .game-card:active { transform: scale(0.98); }

        .gc-left {
            display: flex;
            align-items: center;
            flex-grow: 1;
            overflow: hidden;
        }

        .gc-sno {
            font-weight: bold;
            color: #aaa;
            width: 35px;
            font-size: 14px;
            flex-shrink: 0;
        }

        .gc-info {
            display: flex;
            flex-direction: column;
            justify-content: center;
            width: 100%;
            padding-right: 10px;
        }

        .gc-name {
            font-size: 16px;
            font-weight: 700;
            color: #333;
            text-transform: uppercase;
            margin-bottom: 6px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }

        /* --- NEW TIME LAYOUT STYLES --- */
        .gc-time-container {
            display: flex;
            flex-direction: column; /* Stack vertically by default */
            gap: 4px;
            font-size: 12px;
            color: #555;
        }
        
        .time-row {
            display: flex;
            align-items: center;
        }

        .time-label {
            color: #888;
            font-weight: 500;
            margin-right: 5px;
            min-width: 75px; /* Ensures alignment */
        }
        
        .time-value {
            font-weight: 600;
            color: #444;
        }

        /* --- TOGGLE BUTTON --- */
        .toggle-btn {
            background-color: #28a745; /* GREEN for ON */
            color: white;
            border: none;
            border-radius: 50px;
            padding: 8px 0;
            width: 70px;
            font-size: 13px;
            font-weight: bold;
            text-transform: uppercase;
            cursor: pointer;
            box-shadow: 0 3px 6px rgba(40, 167, 69, 0.3);
            transition: all 0.3s ease;
            text-align: center;
        }

        .toggle-btn.off {
            background-color: #dc3545 !important; /* RED */
            box-shadow: 0 3px 6px rgba(220, 53, 69, 0.3);
        }

        /* --- MOBILE TWEAKS --- */
        @media (max-width: 480px) {
            .main-content { padding: 0 10px; }
            .table-header-row { font-size: 12px; padding: 10px 12px; }
            .game-card { padding: 12px; margin-bottom: 10px; }
            .gc-name { font-size: 15px; }
            
            /* Tweak Time Size for Mobile */
            .gc-time-container { font-size: 11px; }
            .toggle-btn { width: 60px; padding: 6px 0; font-size: 11px; }
            .col-sno, .gc-sno { width: 30px; }
        }
        
        /* Larger screens: Put times side by side if needed */
        @media (min-width: 600px) {
            .gc-time-container {
                flex-direction: row;
                gap: 20px;
            }
        }
    </style>
</head>
<body>

    <div class="page-title">Game Time Table</div>

    <div class="main-content">
        <div class="table-header-row">
            <div class="col-sno">S.No</div>
            <div class="col-game">Game Name & Time</div>
            <div class="col-action">Status</div>
        </div>

        <?php
        function displayGames($con, $table_name, $start_count) {
            $count = $start_count;
            // Fetch games
            $query = "SELECT * FROM `$table_name` ORDER BY sn DESC"; 
            $result = mysqli_query($con, $query);

            while ($row = mysqli_fetch_assoc($result)) {
                $status = $row['active'];
                $btnClass = ($status == 1) ? '' : 'off';
                $btnText = ($status == 1) ? 'ON' : 'OFF';
                
                $openTime = date("h:i A", strtotime($row['open']));
                $closeTime = date("h:i A", strtotime($row['close']));
        ?>
            
            <div class="game-card">
                <div class="gc-left">
                    <div class="gc-sno"><?php echo str_pad($count, 2, '0', STR_PAD_LEFT); ?></div>
                    <div class="gc-info">
                        <span class="gc-name"><?php echo $row['market']; ?></span>
                        
                        <div class="gc-time-container">
                            <div class="time-row">
                                <span class="time-label">Open Time :</span>
                                <span class="time-value"><?php echo $openTime; ?></span>
                            </div>
                            <div class="time-row">
                                <span class="time-label">Close Time :</span>
                                <span class="time-value"><?php echo $closeTime; ?></span>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="gc-right">
                    <button id="btn_<?php echo $row['sn']; ?>_<?php echo $table_name; ?>" 
                            class="toggle-btn <?php echo $btnClass; ?>" 
                            data-sn="<?php echo $row['sn']; ?>" 
                            data-table="<?php echo $table_name; ?>" 
                            data-status="<?php echo $status; ?>"
                            onclick="toggleGame(this)">
                        <?php echo $btnText; ?>
                    </button>
                </div>
            </div>

        <?php
                $count++;
            }
            return $count;
        }

        // Display Tables
        $next_count = 1;
        $next_count = displayGames($con, 'gametime_manual', $next_count);
        displayGames($con, 'gametime_new', $next_count);
        ?>

    </div>

    <?php include('footer.php'); ?>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        function toggleGame(btn) {
            var $btn = $(btn);
            var sn = $btn.data('sn');
            var table = $btn.data('table');
            var currentStatus = $btn.data('status'); // 1 or 0

            // 1. Disable button momentarily to prevent double clicks
            $btn.prop('disabled', true).css('opacity', '0.7');

            // 2. Send Request
            $.ajax({
                url: window.location.href, // Post to self
                type: 'POST',
                data: {
                    action: 'toggle_status',
                    sn: sn,
                    table: table,
                    status: currentStatus
                },
                success: function(response) {
                    var cleanResponse = response.trim(); // Remove whitespace

                    // 3. Check if response is exactly '0' or '1'
                    if (cleanResponse === '0' || cleanResponse === '1') {
                        var newStatus = parseInt(cleanResponse);
                        
                        // Update Data Attribute for next click
                        $btn.data('status', newStatus);

                        // Update Visuals (Green/Red)
                        if (newStatus === 1) {
                            $btn.removeClass('off').text('ON'); // Turns Green
                        } else {
                            $btn.addClass('off').text('OFF'); // Turns Red
                        }
                    } else {
                        // If response is weird, log it
                        console.log("Error Response: " + response);
                        alert("Status update failed. Please refresh.");
                    }
                    $btn.prop('disabled', false).css('opacity', '1');
                },
                error: function() {
                    alert('Internet connection lost or server error.');
                    $btn.prop('disabled', false).css('opacity', '1');
                }
            });
        }
    </script>

</body>
</html>