<?php
// Start output buffering to prevent header HTML from breaking AJAX
ob_start(); 
include('header.php');

// --- AJAX HANDLER FOR STARLINE TIMINGS STATUS TOGGLE ---
if (isset($_POST['action']) && $_POST['action'] == 'toggle_status') {
    // Clear any HTML generated by header.php so we send ONLY the result
    ob_clean(); 
    
    $sn = mysqli_real_escape_string($con, $_POST['sn']);
    $current_status = (int)$_POST['status'];
    
    // Toggle logic: If 1, make 0. If 0, make 1.
    $new_status = ($current_status == 1) ? 0 : 1;
    
    // Update the starline_timings table
    $updateQuery = "UPDATE `starline_timings` SET `active`='$new_status' WHERE `sn`='$sn'";
    
    if (mysqli_query($con, $updateQuery)) {
        echo $new_status; // Send strictly "0" or "1" back to JavaScript
    } else {
        echo "error";
    }
    exit; 
}
ob_end_flush(); 
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Starline Game Timetable</title>
    <style>
        /* --- YOUR REQUESTED CSS STYLE --- */
        body { background-color: #f4f6f9; font-family: 'Segoe UI', Tahoma, sans-serif; margin: 0; padding: 0; }
        
        .page-title {
            text-align: center; font-size: 20px; font-weight: 700; padding: 15px 0;
            background: #7b1fa2; color: #fff;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1); position: sticky; top: 0; z-index: 100; margin-bottom: 20px;
        }

        .main-content { max-width: 800px; margin: 0 auto; padding: 0 15px; }

        .table-header-row {
            background-color: #9c27b0; color: white; display: flex; align-items: center;
            padding: 12px 15px; font-weight: 600; font-size: 14px; border-radius: 8px;
            margin-bottom: 10px; box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }

        .col-sno { width: 10%; text-align: left; }
        .col-game { width: 65%; text-align: left; }
        .col-action { width: 25%; text-align: right; }

        .game-card {
            background: #ffffff; border-radius: 12px; padding: 15px; margin-bottom: 12px;
            display: flex; align-items: center; justify-content: space-between;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08); border-left: 5px solid #9c27b0;
        }

        .gc-left { display: flex; align-items: center; flex-grow: 1; }
        .gc-sno { font-weight: bold; color: #aaa; width: 35px; font-size: 14px; }
        .gc-info { display: flex; flex-direction: column; }
        .gc-name { font-size: 16px; font-weight: 700; color: #333; text-transform: uppercase; }
        .gc-time { font-size: 12px; color: #7b1fa2; font-weight: 600; margin-top: 2px; }

        .toggle-btn {
            background-color: #28a745; color: white; border: none; border-radius: 50px;
            padding: 8px 0; width: 85px; font-size: 12px; font-weight: bold;
            text-transform: uppercase; cursor: pointer; transition: all 0.3s ease; text-align: center;
        }

        .toggle-btn.off { background-color: #dc3545 !important; }

        @media (max-width: 480px) {
            .gc-name { font-size: 14px; }
            .toggle-btn { width: 75px; font-size: 11px; }
        }
    </style>
</head>
<body>

    <div class="page-title">Starline Market Timing & Status</div>

    <div class="main-content">
        <div class="table-header-row">
            <div class="col-sno">#</div>
            <div class="col-game">Market Details</div>
            <div class="col-action">Status</div>
        </div>

        <?php
        $count = 1;
        // Fetching from starline_timings as requested
        $query = "SELECT * FROM `starline_timings` ORDER BY close ASC"; 
        $result = mysqli_query($con, $query);

        if (mysqli_num_rows($result) > 0) {
            while ($row = mysqli_fetch_assoc($result)) {
                $status = $row['active'];
                $btnClass = ($status == 1) ? '' : 'off';
                $btnText = ($status == 1) ? 'ON' : 'OFF';
                $displayTime = date("h:i A", strtotime($row['close']));
        ?>
            
            <div class="game-card">
                <div class="gc-left">
                    <div class="gc-sno"><?php echo $count; ?></div>
                    <div class="gc-info">
                        <span class="gc-name"><?php echo $row['name']; ?></span>
                        <span class="gc-time">Closing Time: <?php echo $displayTime; ?></span>
                    </div>
                </div>
                <div class="gc-right">
                    <button class="toggle-btn <?php echo $btnClass; ?>" 
                            data-sn="<?php echo $row['sn']; ?>" 
                            data-status="<?php echo $status; ?>"
                            onclick="toggleStarline(this)">
                        <?php echo $btnText; ?>
                    </button>
                </div>
            </div>

        <?php
                $count++;
            }
        } else {
            echo "<div style='text-align:center; padding:20px; color:#999;'>No Starline Timings found.</div>";
        }
        ?>

    </div>

    <?php include('footer.php'); ?>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        function toggleStarline(btn) {
            var $btn = $(btn);
            var sn = $btn.data('sn');
            var currentStatus = $btn.data('status');

            $btn.prop('disabled', true).css('opacity', '0.6');

            $.ajax({
                url: window.location.href,
                type: 'POST',
                data: {
                    action: 'toggle_status',
                    sn: sn,
                    status: currentStatus
                },
                success: function(response) {
                    var cleanResponse = response.trim();

                    if (cleanResponse === '0' || cleanResponse === '1') {
                        var newStatus = parseInt(cleanResponse);
                        $btn.data('status', newStatus);

                        if (newStatus === 1) {
                            $btn.removeClass('off').text('ON');
                        } else {
                            $btn.addClass('off').text('OFF');
                        }
                    } else {
                        alert("Update failed.");
                    }
                    $btn.prop('disabled', false).css('opacity', '1');
                },
                error: function() {
                    alert('Error connecting to server.');
                    $btn.prop('disabled', false).css('opacity', '1');
                }
            });
        }
    </script>
</body>
</html>